CHART_CATEGORY: "FED"
TEST_CYCLE: "CCAR_2023"
FILE_NAME_MAPPING:
    SCENARIOS:
        Historic: "historic"
        Internal Baseline: "baseline"
        Severely Adverse: "adverse"
    ECONOMIC_SCOPES:
        Domestic: "domestic"
        International: "international"
VARIABLE_NUMBER_2_CAR_VARIABLE_NAME: # to potrzebowałbym z DB
    153: "Euro Zone - National Accounts: Real GDP, (bill. 2010 EUR, CADARSAAR), Ann. % Ch_Stock"